# MkDocs configuration for builds with material theme

INHERIT: mkdocs-base.yml

site_url: "https://docs.percona.com/percona-link-mongodb"


theme:
  name: material
  custom_dir: _resource/overrides

  
#Google Analytics configuration 
extra: 
  analytics: 
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

            

